Do not validate extension against the latest buildkit version when installing
Do not validate extension against the latest buildkit version when installing.
This allows for installing older extension versions. The command will
fail at the `apt install` if the version doesn't exist:

```
$ pgxman install pgvector=1@15
The following Debian packages will be installed:
  postgresql-15-pgxman-pgvector=1
The following Apt repositories will be added or updated:
  pgxman-core
Do you want to continue? [Y/n] Y
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm-updates InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 https://apt.postgresql.org/pub/repos/apt bookworm-pgdg InRelease
Get:5 https://pgxman-buildkit-debian.s3.amazonaws.com/debian bookworm InRelease [3244 B]
Get:6 https://pgxman-buildkit-debian.s3.amazonaws.com/debian bookworm/main arm64 Packages [4535 B]
Fetched 7779 B in 1s (11.9 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package postgresql-15-pgxman-pgvector is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Version '1' for 'postgresql-15-pgxman-pgvector' was not found
Error: apt install: exit status 100
Usage:
  pgxman install [flags]
```