[HYD-597] Warn pg not installed if `pg_config` can not be found (#90)
* Warn pg not installed if `pg_config` can not be found

```
root@afb612e26230:/# pgxman install pgvector --pg 12
Error: could not detect an installation of Postgres 12. For information on installing Postgres, see: https://docs.pgxman.com/installing_postgres
Usage:
  pgxman install [flags]

Examples:
  # Install the latest pgvector for the installed PostgreSQL.
  # PostgreSQL version is detected from pg_config if it exists,
  # Otherwise, the latest supported PostgreSQL version is used.
  pgxman install pgvector

  # Install the latest pgvector for PostgreSQL 15
  pgxman install pgvector --pg 15

  # Install pgvector 0.5.0 for PostgreSQL 15
  pgxman install pgvector=0.5.0 --pg 15

  # Install pgvector 0.5.0 for PostgreSQL 15 with sudo
  pgxman install pgvector=0.5.0 --pg 15 --sudo

  # Install pgvector 0.5.0 and postgis 3.3.3 for PostgreSQL 15
  pgxman install pgvector=0.5.0 postgis=3.3.3 --pg 15

  # Install from a local Debian package
  pgxman install /PATH_TO/postgresql-15-pgxman-pgvector_0.5.0_arm64.deb

Flags:
  -h, --help        help for install
      --pg string   Install the extension for the PostgreSQL version. It detects the version by pg_config if it exists. Supported values are 13, 14, 15, 16.
      --sudo        Run the underlaying package manager command with sudo.
  -y, --yes         Automatic yes to prompts and run install non-interactively.

Global Flags:
      --debug   enable debug logging

Error: could not detect an installation of Postgres 12. For information on installing Postgres, see: https://docs.pgxman.com/installing_postgres

```

* Don't print duplicated error

* Add period to error

* Slience usage when errors

* Fix typo in error checking

* Don't share install pg version flag